version: '3'
services:
  flask-app:
    build:
      context: /share/CACHEDEV1_DATA/Web/Geek-Compagnon/
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1